blank_issues_enabled: false
contact_links:
  - name: 💡 Suggerimenti & Idee
    url: https://github.com/Pioshin/writers-nexus/discussions
    about: Condividi suggerimenti e discutine con la community.
